# Numele microserviciului
spring.application.name=auth-service

# Portul pe care va rula (astfel nu se bate cu celelalte)
server.port=8085

# Conexiunea la baza de date PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# Set?ri Hibernate - "update" va crea automat tabelul "users" bazat pe clasa pe care ?i-am dat-o
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true