spring.application.name=doctor-service
# Portul pe care ruleaz? serviciul (conform docker-compose-ului t?u)
server.port=8083

# Configurarea conexiunii la PostgreSQL
# ATEN?IE: Schimb? parola cu cea setat? de tine local, dac? rulezi direct din IntelliJ.
# Dac? rulezi prin Docker, po?i schimba 'localhost' cu numele containerului ('db-postgres')
spring.datasource.url=jdbc:postgresql://localhost:5432/doctor_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate - creeaz? automat tabelele pe baza entit??ii
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect