spring.application.name=doctor-service
server.port=8083
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/doctor_db}
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update