spring.application.name=patient-service
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/patient_db}
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update