spring.application.name=appointment-service
server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/appointment_db}
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update
patient.service.url=${PATIENT_SERVICE_URL:http://localhost:8081}
doctor.service.url=${DOCTOR_SERVICE_URL:http://localhost:8083}